#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
