#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
# required:The redirection must be a "301 Moved Permanently"

apt-get update
apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/;
    }
}" > /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
