#!/usr/bin/env bash

# configure web-02 to be identical to web-01
# Since we're placing our web servers behind a load balancer for this project,
# we want to add a custom Nginx response header. The goal here is to be able to track which
# web server is answering our HTTP requests, to understand and track the way a load balancer works.

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
cd /var/www/html; touch index.html 404.html
echo "Hello World!" > index.html
echo "Ceci n'est pas une page" > 404.html;
printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm;
	location /redirect_me {
	return 301 https://www.youtube.com;
	}

	error_page 404 /404.html;

	location /404 {
	root /var/www/html;
	internal;
	}

}" > /etc/nginx/sites-available/default

service nginx restart
