#!/usr/bin/env bash

# find out what's keeping your Ubuntu container's Nginx installation
# from listening on port 80
# Nginx must be running, and listening on port 80 of all the server's
# active IPv4 IPs
# Write a Bash script that configures a server to the above requirements

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
