#!/usr/bin/env bash
# a bash script that configures nginx to run and listen to port 80
rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
