#!/usr/bin/env bash
# a bash script that configures nginx to run and listen to port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep nginx | head -1)"
