#!/usr/bin/env bash
# a Bash script that displays: "To infinity and beyond indefinitely"
# With a "sleep 2" in between each iteration, "I am invincible!!!" when receiving a SIGTERM signal
i=0
trap 'echo "I am invincible!!!"' SIGTERM 
while (( i == 0 )); do
  echo "To infinity and beyond indefinitely"
  sleep 2
done
