#!/usr/bin/env bash
# display hours from 0 to 12 and minutes from 1 to 59
hour=0
while (( hour < 13)); do
  echo "Hour: $hour"
  minute=1
  while (( minute < 60 )); do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
