#!/usr/bin/env bash
# connect to a server without typing a password. Share your
# SSH client configuration in your answer file.
# Your SSH client configuration must be configured to use the
# private key ~/.ssh/school
# Your SSH client configuration must be configured to refuse to
# authenticate using a password

Host *
      PasswordAuthentication no
      IdentifyFile ~/.ssh/school
